name: select_field
description: A highly customizable, simple and easy to use Flutter widget for creating a dropdown list of options that users can select from.
version: 0.0.1
homepage: https://github.com/Boykista/select_field

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
