name: select_field
description: Simple, easy and highly customizable input field for creating a dropdown list of selectable options.
version: 0.1.2
homepage: https://github.com/Boykista/select_field
repository: https://github.com/Boykista/select_field

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
